<?php include_once ("includes/header.php");?>

<?php include_once ("includes/nav.php");?>
      
	<div id="primary" class="content-area">
		<div id="sitetitle" class="site-header">
      <h2 class="department"><a href="http://herbarium.utk.edu/" title="University of Tennessee Herbarium - TENN" rel="home">UT Herbarium - TENN</a>
       <small><a href="http://artsci.utk.edu">College of Arts &amp; Sciences</a></small> </h2> 
		</div>


                    <!-- Would you like a big image. This is where you'd put it. -->

<!--    <div class="entry-thumbnail"><img src="images/main.png" class="attachment-large wp-post-image" alt="Magnolia Blossoms" style="width:100%;" /></div>-->


		
		
		<div id="content" class="site-content site-content wide" role="main">

				<article class="hentry">

                <!-- And here begins the Content area. This is where you place your content -->

								<div class="entry-content reg">
                  <header class="entry-header"><h1 class="entry-title">Contents and Usage</h1>
                  </header>
								  <p><STRONG></STRONG>TENN herbarium databases are updated frequently for online use. Searching or browsing results from theVascular Plants occurrence  database are listed alphabetically in  full scientific name by each taxon in either family name or genus name  order. Common name(s) and synonym(s) if any will be listed beneath each  scientific name in the name list. Each genus name heading also  contains links to view photographs and/or distribution maps of the taxon. All species  listed are also hyperlinked to give the same  information mentioned above.</p>
									<p>Photographs and their thumbnails are scanned and produced from the TENN  herbarium's archived slides, TENN herbarium's mounted specimens, or from professional and amateur botanists who submit their photographs for inclusion on the website. Distribution maps are generated by hand with Photoshop  and periodically  updated. Vector based mapping will be fully implemented with ArcGIS in the future.</p>
									<p>Online publications are done via real-time ODBC connections.  Search queries are performed based on the Structured Query Language  (SQL)  generated on the fly and directly accesses our most current online  database. A select few pages also requires the use of client side  JavaScript  so please ensure your browse supports this feature.</p>
									<p>Searching or browsing the Fungus collections database will yield a list of all taxa  that meets the fungus criteria. The results are listed alphabetically in  the full scientific name based on location of collection or type. Beneath  each name listing, a taxon's location and date of collection will be  printed. Accession numbers are also listed with each record set.  Searching by genus name is allowed under both search by country and browse by  type.</p>
									<!-- And here are a couple of helpers to get you started in page layout -->
									  <!-- Whenever you need to begin a fresh 'new row' of content. Add br with the class of clear  -->
									  
									  <br class="clear">
								  
				  </div><!-- .entry-content -->
                <!-- And here begins the Content area. This is where you place your content -->
						
					<footer class="entry-meta">

          </footer><!-- .entry-meta -->
				</article><!-- #post -->

			
		</div>



                <!-- If you would like to have an 'expanded footer' (four columns of supplementary content) you should place it here.  -->
                <!-- For a sample of the Expanded footer's HTML, check the `/library/partials/` directory.  -->




	</div><!-- #primary -->
</div><!-- .main-content -->

    <footer id="colophon" class="site-footer" role="contentinfo">

                <!-- If you would like to have an 'expanded footer' (four columns of supplementary content) you should place it here.  -->
                <!-- For a sample of the Expanded footer's HTML, check the `/library/partials/` directory.  -->

    
  <?php include_once ("includes/footer.php");?>