
<div id="slider" class="nivoSlider">
            <img src="images/ac_unci5.jpg" />
            <img src="images/aescglab.jpg" />
            <img src="images/ap_hyem1.jpg" />
            <img src="images/aronmela3.jpg" />
            <img src="images/calyflor2.jpg" />
            <img src="images/castdent5.jpg" />
            <img src="images/cl_glau4.jpg" />
            <img src="images/cornamom2.jpg" />
            <img src="images/cy_kent5.jpg" />
            <img src="images/fagugran4.jpg" />
            <img src="images/ga_spec2.jpg" />
            <img src="images/gledtria3.jpg" />
            <img src="images/leucrecu2.jpg" />
            <img src="images/lirituli3.jpg" />
            <img src="images/nyssaqua.jpg" />
            <img src="images/ox_viol3.jpg" />
            <img src="images/ph_amoe4.jpg" />
            <img src="images/po_amph2.jpg" />
            <img src="images/prunpers.jpg" />
            <img src="images/rhodperi3.jpg" />
            <img src="images/rububifr2.jpg" />
            <img src="images/smillaur.jpg" />
            <img src="images/taxucana2.jpg" />
            <img src="images/vacccory.jpg" />
            <img src="images/xantsimp2.jpg" />
            <img src="images/zantamer.jpg" />
</div> 
